### ISSUE TITLE
geo.GetMetro

### ISSUE THREAD

**Issue by lucksp** [maxkueng/node-lastfmapi#6]
is this feature disabled by lastFM?

**Comment by maxkueng** [comment]
It looks like they've removed it. According to the [Last.fm API docs](http://www.last.fm/api) the `geo` namespace only has `geo.getTopArtists` and `geo.getTopTracks`.

It's quite possible that some of the methods in this library are out-of-date and no longer exist or need a fix. The Last.fm people keep changing things without changing the API version number and I don't actively keep track of what they're doing.

I'm going to remove the metro methods from the `geo` namespace.

If you encounter more problems feel free to file issues or make pull requests.

**Comment by maxkueng** [comment]
It turns out that there were a whole bunch of API methods that Last.fm had silently removed from their service. I've removed them all in commit e88b0a5. A new version is available on npm.

This includes `geo.getEvents()` that you're using. While the method still seems to work it probably doesn't return any up-to-date data as it has been removed from the docs. Everything regarding events is gone. Maybe you can find another service to get event-related data. Maybe [Songkick](http://www.songkick.com/developer)?

Here's a list of all the API methods that no longer exist:

 - `album.getBuylinks()`
 - `album.getShouts()`
 - `album.share()`
 - `artist.getEvents()`
 - `artist.getPastEvent()`
 - `artist.getPodcasts()`
 - `artist.getShouts()`
 - `artist.getTopFans()`
 - `artist.share()`
 - `artist.shout()`
 - `chart.getHypedTracks()`
 - `chart.getLovedTracks()`
 - `event.*`
 - `geo.getEvents()`
 - `geo.getMetro*()`
 - `group.*`
 - `library.addAlbum()`
 - `library.addArtist()`
 - `library.addTrack()`
 - `library.getAlbums()`
 - `library.getTracks()`
 - `library.removeAlbum()`
 - `library.removeArtist()`
 - `library.removeScrobble()`
 - `library.removeTrack()`
 - `playlist.*`
 - `radio.*`
 - `tag.getWeeklyArtistChart()`
 - `tag.search()`
 - `tasteometer.*`
 - `track.ban()`
 - `track.getBuylinks()`
 - `track.getFingerprintMetadata()`
 - `track.getShouts()`
 - `track.getTopFans()`
 - `track.share()`
 - `track.unban()`
 - `user.getBannedTracks()`
 - `user.getEvents()`
 - `user.getNeighbours()`
 - `user.getNewReleases()`
 - `user.getPastEvents()`
 - `user.getPlaylists()`
 - `user.getRecentStations()`
 - `user.getRecommendedArtists()`
 - `user.getRecommendedEvents()`
 - `user.getShouts()`
 - `user.shout()`
 - `venue.*`
